### ISSUE TITLE
Error 404: https://bearsampp.com/doc/?utm_source=bearsampp-2022.08.09

### ISSUE THREAD

**Issue by alain01** [Bearsampp/Bearsampp#168] opened 2022-08-11 09:19 UTC
Bearsampp version:
2022.08.09

Right click on bearswampp icon on the bottom nav then choose "Help" => 404 error
https://bearsampp.com/doc/?utm_source=bearsampp-2022.08.09

**Comment by N6REJ** [comment] 2022-08-11 16:03
damn it.. I thought we had all those fixed.. *sigh*...

**Comment by N6REJ** [comment] 2022-08-12 09:07
This is caused by line 170
```             TplAestan::getItemLink($bearsamppLang->getValue(Lang::HELP), Util::getWebsiteUrl('doc')) . PHP_EOL . ```
in core->tpls->class.tpl.app.php needs to be set to "faq"
```             TplAestan::getItemLink($bearsamppLang->getValue(Lang::HELP), Util::getWebsiteUrl('faq')) . PHP_EOL . ```

**Comment by N6REJ** [comment] 2022-08-14 10:26
Fixed in https://github.com/Bearsampp/Bearsampp/pull/182

**Closed by N6REJ** 2022-08-14 10:26 UTC
Labels: :bug: bug, :triangular_flag_on_post: Blocker
